name: Create Azure Storage Account and Blob Container
uses: tjd399/Azure-Storage-and-Container-Creation@main

on:
  workflow_dispatch:
  push:
    branches:
      - main
   
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      run:
      - name: checkout code
        uses: actions/checkout@v1
     # - name:  Create Azure Storage Account and Blob Container 


      - name: Azure Login
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}


      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan
