name: Create Azure Storage Account and Blob Container

on:
  workflow_dispatch:
  inputs:
   subscription_id:
        description: 'Subscription ID'
        required: true
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        uses: azure/CLI@v1
        with:
          inlineScript: 'az account set --subscription ${{ github.event.inputs.subscription_id }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan
      
     # - name: Create Azure Resources
      #  run: |
       #   cd terraform
        #  terraform apply 
      
     # - name: Terraform Apply
      #   run: terraform apply 